---
title: "Pearl Harbor Newspaper Content Analysis"
author: "Elise Hachfeld and Theresa Worden"
output: 
  flexdashboard::flex_dashboard:
    #vertical_layout: scroll
    theme:
      version: 4
      bootswatch: lux
runtime: shiny
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Import data here
```

About
==========================

Column {data-width=500}
-------------------------------------

### Box 1
Talk about the purpose of the project here.


Column {data-width=500}
-------------------------------------
### Box 2
Talk about the Library of Congress API here. 


Section 1
==========================

Column {data-width=400}
-------------------------------------
   
### Box 1

```{r eruptions, echo=FALSE}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

### Parameters
```{r}
#Add code for adjusting data here
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)
```


Column {data-width=300}
-------------------------------------
### Box 3
Talk about the graph here.


Section 2
==========================
   
Row {.tabset .tabset-fade}
-------------------------------------
   
### Box 1

```{r eruptions2, echo=FALSE}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```
 
### Box 2
    
```{r eruptions3, echo=FALSE}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

Row
-------------------------------------
### Box 3
Talk about the graph here.

### Parameters
```{r}
#Add code for adjusting data here
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)
```


Section 3
==========================


Section 4
==========================

