---
title: "newspapers"
author: "Elise Hachfeld"
date: "2024-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr2)
library(jsonlite)
```

```{r}
base_url <- "https://www.loc.gov/collections/chronicling-america/"
final_results <- data.frame()

get_json_data <- function(params) {
  req <- request(base_url) |>
    req_throttle(rate = 20/10) |>
    req_url_query(!!!params)
  
  response <- req |>
    req_perform() |>
    resp_body_string() |>
    fromJSON()
  
  return(response)
}

parse_json_data <- function(response) {
  data <- flatten(response$results)
  has_more <- !is.null(response$pagination["next"][[1]])
  print(paste0(response$pagination$to, "/", response$pagination$of))
  print(paste0("Has more pages: ", has_more))
  mylist <- list(data, has_more)
  return(mylist)
}
```

```{r}
get_paginated_data <- function(display_level = "page",
                          start_date = "",
                          end_date = "",
                          location_state = "",
                          search_type = "advanced",
                          sp = "1",
                          fa = "",
                          front_pages_only = "true"){
  final_results <- data.frame()
  page <- 1
  has_more <- TRUE
  
   while (has_more) {
     print(paste0("Getting page ", page, "..."))
     
       # Set the query parameters
       params <-  list(dl = display_level,
                  start_date = start_date,
                  end_date = end_date,
                  number_page = page,
                  searchType = search_type,
                  front_pages_only = front_pages_only,
                  sp = page,
                  fa = fa,
                  fo = "json",
                  at = "results,pagination")
       
     response <- get_json_data(params)
     mylist <- parse_json_data(response)
     
     parsed <- mylist[[1]]
     has_more <- mylist[[2]]
     
     final_results <- bind_rows(final_results, parsed)

     page <- page + 1
   }
  print(paste0("Number of results: ", nrow(final_results)))
  final_results <<- final_results
}
```

```{r}
get_paginated_data(start_date = "1941-01-01",
                   end_date = "1942-12-31",
                   location_state = "",
                   fa = "language:english")



data_1939 <- get_paginated_data(start_date = "1939-01-01",
                   end_date = "1939-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1939, "data_1939.rds")

data_1940 <- get_paginated_data(start_date = "1940-01-01",
                   end_date = "1940-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1940, "data_1940.rds")

data_1941 <- get_paginated_data(start_date = "1941-01-01",
                   end_date = "1941-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1941, "data_1941.rds")

data_1942 <- get_paginated_data(start_date = "1942-01-01",
                   end_date = "1942-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1942, "data_1942.rds")

data_1943 <- get_paginated_data(start_date = "1943-01-01",
                   end_date = "1943-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1943, "data_1943.rds")

data_1944 <- get_paginated_data(start_date = "1944-01-01",
                   end_date = "1944-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1944, "data_1944.rds")

data_1945 <- get_paginated_data(start_date = "1945-01-01",
                   end_date = "1945-12-31",
                   location_state = "",
                   fa = "language:english")

saveRDS(data_1945, "data_1945.rds")
```

```{r}
data_clean <- final_results |>
  select(index, date, title, partof_title, description, url, image_url, language, location_state, location_county, location_city, contributor, publication_frequency, subject, subject_ethnicity)

data_clean <- data_clean |>
  mutate(across(where(is.list) & !all_of("subject"),
                ~ sapply(.x, function(val) paste(val, collapse = ', ')))) |>
  
  mutate(language = str_remove(language, "[, ]?english[, ]?"),
         language = str_remove(language, ","),
         language = str_trim(language)) |>
  
  rename(newspaper_title = partof_title,
         text_data = description,
         state = location_state,
         city = location_city,
         other_language = language) |>
  
  mutate(across(everything(), ~ ifelse(. == "", NA, .))) |>
  mutate(across(everything(), ~ ifelse(. == "NULL", NA, .))) |>
  mutate(as_date = ymd(date))

write.csv(data_clean,"~/Code/R/data_sci_fall/Data/clean_data.csv", row.names = FALSE)
```

```{r}
newspapers <- unique(data_clean$newspaper_title)
print(newspapers)

languages <- unique(data_clean$other_language)
print(languages)

ethnicities <- unique(data_clean$subject_ethnicity)
print(ethnicities)

# Data frame where each subject has its own row
data_subjects <- data_clean |>
  unnest(subject)

subjects <- data_subjects |>
  distinct(subject) |>
  pull(subject)
print(unique_subjects)

# View most common subjects
data_subjects |>
  count(subject, sort = TRUE)
```

```{r}
all_states <- data_clean |>
  
  
unnest_tokens(word, description, token = "words") |>
```